[package]
name = "pasto"
version = "0.1.0"
edition = "2021"
description = "Parser for Vaca, generates an AST-like structure"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
