[package]
name = "chifre"
version = "0.1.0"
edition = "2021"
description = "Lexer for Vaca"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.7.6"
pest_derive = "2.7.6"
