[package]
name = "casco"
version = "0.1.0"
edition = "2021"
description = "CLI tool to use Vaca"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
