[package]
name = "vaca-core"
version = "0.6.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.7.6"
rustc-hash = "1.1.0"
speedy = "0.8.7"
