[package]
name = "vaca-build"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.7.6"
pest_derive = "2.7.6"
speedy = "0.8.7"
rustc-hash = "1.1.0"
vaca-core = { path = "../vaca-core" }
