[package]
name = "vaca-stl"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.8.1"
vaca-core ={ path = "../vaca-core" }
